### ISSUE TITLE
remove dates

### ISSUE THREAD

**Issue by ryw** [astronomerio/airflow_guides#1]
we want guides to be evergreen content, shouldn't require a date in the front-matter... does builder require it? if not, let's edit the guides to remove the dates.

**Comment by gregbrunk** [comment]
Builder needs - it’s  not displayed anywhere in UI but is still important for frontmatter.

**Comment by gregbrunk** [comment]
It doesn’t technically need one - it just uses one right now when it’s mapping the library of guides, along with the other frontmatter fields. Someone needs to just add `! == null` type logic to the map, or strip out all references to date. I only put it in cuz it seems a little cray to have a library of content with no date field in case we ever wanted to sort or reference age or publish new versions or whatever. We can strip it out for sure, it just needs to happen on both the site and guides repo so it doesn’t break the map.

**Comment by gregbrunk** [comment]
Would rather figure out a way to hide the frontmatter so we can keep a publish date around in case we ever need them for reasons other than display
